// <auto-generated />
using System;
using CSGO_Float_Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSGO_Float_Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210722005542_createdb")]
    partial class createdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("CSGO_Float_Api.Models.FloatRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("FloatRequests");
                });

            modelBuilder.Entity("CSGO_Float_Api.Models.Skin", b =>
                {
                    b.Property<ulong>("param_a")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Float")
                        .HasColumnType("REAL");

                    b.Property<int?>("FloatRequestID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("param_d")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("param_m")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("param_s")
                        .HasColumnType("INTEGER");

                    b.HasKey("param_a");

                    b.HasIndex("FloatRequestID");

                    b.ToTable("Skins");
                });

            modelBuilder.Entity("CSGO_Float_Api.Models.SteamAccount", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("SentryFileBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shared_secret")
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("SteamAccounts");
                });

            modelBuilder.Entity("CSGO_Float_Api.Models.Skin", b =>
                {
                    b.HasOne("CSGO_Float_Api.Models.FloatRequest", null)
                        .WithMany("Skins")
                        .HasForeignKey("FloatRequestID");
                });

            modelBuilder.Entity("CSGO_Float_Api.Models.FloatRequest", b =>
                {
                    b.Navigation("Skins");
                });
#pragma warning restore 612, 618
        }
    }
}
